name: Check PR

on:
  # Triggers the workflow on every pull request to master branch
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Android/MSTG-Android-Kotlin-App

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the app
        run: ./gradlew assembleRelease
        
      - name: List Downloaded document (sampling of download-artifact)
        run: ls -la 
        
      - name: Rename build 
        run: mv ./app/build/outputs/apk/release/app-release-unsigned.apk ./app/build/outputs/apk/release/MASTG-Android.apk

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ./Android/MSTG-Android-Kotlin-App/app/build/outputs/apk/release/MASTG-Android.apk
      
  release:
    runs-on: ubuntu-latest
    needs: [build]
    #if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
      - name: List Downloaded document (sampling of download-artifact)
        run: ls -l 

      - name: print working directory
        run: pwd 
      - name: Listing of root directory
        run: ls -l 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          draft: true
          generate_release_notes: true
          files: |
            app-release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
